калькулятор исправленный
js-tasks-ru/jsbasic-20221215_elena-g-starikova pull request #7
Opened 2022-12-29 07:36 UTC by ElenaStarikova

2022-12-29 07:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-09 08:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-09 08:57 UTC, koalex requested changes

2023-01-09 08:57 UTC, koalex commented on 2-module/3-task/index.js
> +    this.a = a,
запятые заменить на `;`

2023-01-09 10:08 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-09 10:44 UTC, koalex approved these changes

2023-01-09 10:44 UTC, merged